image: blang/latex
Build:
  stage: build
  script:
    - latexmk -pdf -cd docs/dissertation/dissertation.tex
  artifacts:
    paths:
     - "*.pdf"
Test:
  stage: test
  script:
    - cd Game
    - pip3 install -r requirements.txt
    - xvfb-run python3 tests.py




